# Generated by Django 5.1.15 on 2026-06-20 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='полное имя')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес доставки по умолчанию')),
                ('experience_level', models.CharField(choices=[('beginner', 'Новичок'), ('practitioner', 'Практикующий'), ('instructor', 'Инструктор')], default='beginner', max_length=20, verbose_name='уровень практики')),
                ('favorite_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shop.category', verbose_name='любимая категория товаров')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
